---
name: xconv2
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.12
  - pip !=21.3
  - cartopy  # no pip wheel
  - fsspec
  - pandas
  - paramiko
  - pyside6
  - s3fs
  - setuptools >80  # cfplot imports distutils
  - superqt
  - pyside6
  - esmpy
  - udunits2  # no pip wheel; required by cf-python/cf-units
  - zarr
  - rdflib
  - prov
  - pyfive 
  # testing
  - pytest
  # move these to conda-forge deps when released
  - pip:
      - "cfdm @ git+https://github.com/davidhassell/cfdm.git@pyfive-netcdf"
      - "cf-python @ git+https://github.com/davidhassell/cf-python.git@kerchunk-read"
      - "cf-plot @git+https://github.com/bnlawrence/cf-plot.git@main"
      - "ppfive @git+https://github.com/NCAS-CMS/ppfive.git@main"
      - "p5rem @git+https://github.com/NCAS-CMS/p5rem.git@main"

      - "-e ."  # xconv2 is not yet on conda-forge
