---
name: xconv2
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.12
  - pip !=21.3
  - cartopy  # no pip wheel
  - cf-python >=3.21.0
  - esmpy
  - fsspec
  - numpy
  - pandas
  - paramiko
  - prov
  - pyfive >=1.2.0
  - pyside6
  - rdflib
  - s3fs
  - setuptools >80  # cfplot imports distutils
  - superqt
  - udunits2  # no pip wheel; required by cf-python/cf-units
  - umfive >=0.2.2
  - zarr 
  # testing
  - pytest
  # move these to conda-forge deps when released
  - pip:
      - "cf-plot @git+https://github.com/bnlawrence/cf-plot.git@main"
      - "p5rem @git+https://github.com/NCAS-CMS/p5rem.git@main"
      - "-e ."  # xconv2 is not yet on conda-forge
