---
name: xconv2-integration
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.12,<3.14
  - pip !=21.3
  - cartopy  # no pip wheel
  - udunits2  # no pip wheel; required by cf-python/cf-units
  - cf-plot
  - pandas
  - pyside6
  - setuptools >80
  - superqt
  - zarr
  - pytest
  - pip
  - pip:
      - "git+https://github.com/ncas-cms/cfdm.git@main"
      - "git+https://github.com/ncas-cms/cf-python.git@main"
      - "-e ."  # xconv2 is not yet on conda-forge
      - docker
      - minio
